### ISSUE TITLE
Option to use a different sound for up beat

### ISSUE THREAD

**Issue by theaquarium** [TheAndroidMaster/Metronome-Android#11]
Maybe a toggle switch in settings to have the pitch of the sound be different on the up beat like in other metronome apps.

**Comment by fennifith** [comment]
Previously the sound was set to ~half the max value and would increase on an upbeat, but people were complaining about the sound being too quiet (#10), so in commit 42f94a5 I just set it to use a higher frequency on the upbeat and always play at max volume instead, with no option in the settings.

If the users complain about this change I might go back and add an option, but I'd prefer not to.
